apiVersion: apps/v1
kind: Deployment
metadata:
  name: baza-frontend
  labels:
    app: baza-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: baza-frontend
  template:
    metadata:
      labels:
        app: baza-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PENPOT_PUBLIC_URI
              value: {{ .Values.baza.publicUri | quote }}
            - name: PENPOT_FLAGS
              value: "disable-email-verification enable-smtp enable-prepl-server"
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: baza-frontend
spec:
  selector:
    app: baza-frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
